global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service-discovery'
    static_configs:
      - targets: ['service-discovery:8761']

  - job_name: 'config-server'
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8082']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'file-storage-service'
    static_configs:
      - targets: ['file-storage-service:8084']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8085']

  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:8086']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8087']
